 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/accreditations", type: :request do
  # Accreditation. As you add validations to Accreditation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Accreditation.create! valid_attributes
      get accreditations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      accreditation = Accreditation.create! valid_attributes
      get accreditation_url(accreditation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_accreditation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      accreditation = Accreditation.create! valid_attributes
      get edit_accreditation_url(accreditation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Accreditation" do
        expect {
          post accreditations_url, params: { accreditation: valid_attributes }
        }.to change(Accreditation, :count).by(1)
      end

      it "redirects to the created accreditation" do
        post accreditations_url, params: { accreditation: valid_attributes }
        expect(response).to redirect_to(accreditation_url(Accreditation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Accreditation" do
        expect {
          post accreditations_url, params: { accreditation: invalid_attributes }
        }.to change(Accreditation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post accreditations_url, params: { accreditation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested accreditation" do
        accreditation = Accreditation.create! valid_attributes
        patch accreditation_url(accreditation), params: { accreditation: new_attributes }
        accreditation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the accreditation" do
        accreditation = Accreditation.create! valid_attributes
        patch accreditation_url(accreditation), params: { accreditation: new_attributes }
        accreditation.reload
        expect(response).to redirect_to(accreditation_url(accreditation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        accreditation = Accreditation.create! valid_attributes
        patch accreditation_url(accreditation), params: { accreditation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested accreditation" do
      accreditation = Accreditation.create! valid_attributes
      expect {
        delete accreditation_url(accreditation)
      }.to change(Accreditation, :count).by(-1)
    end

    it "redirects to the accreditations list" do
      accreditation = Accreditation.create! valid_attributes
      delete accreditation_url(accreditation)
      expect(response).to redirect_to(accreditations_url)
    end
  end
end
