 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/diaria", type: :request do
  # Diarium. As you add validations to Diarium, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Diarium.create! valid_attributes
      get diaria_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      diarium = Diarium.create! valid_attributes
      get diarium_url(diarium)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_diarium_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      diarium = Diarium.create! valid_attributes
      get edit_diarium_url(diarium)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Diarium" do
        expect {
          post diaria_url, params: { diarium: valid_attributes }
        }.to change(Diarium, :count).by(1)
      end

      it "redirects to the created diarium" do
        post diaria_url, params: { diarium: valid_attributes }
        expect(response).to redirect_to(diarium_url(Diarium.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Diarium" do
        expect {
          post diaria_url, params: { diarium: invalid_attributes }
        }.to change(Diarium, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post diaria_url, params: { diarium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested diarium" do
        diarium = Diarium.create! valid_attributes
        patch diarium_url(diarium), params: { diarium: new_attributes }
        diarium.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the diarium" do
        diarium = Diarium.create! valid_attributes
        patch diarium_url(diarium), params: { diarium: new_attributes }
        diarium.reload
        expect(response).to redirect_to(diarium_url(diarium))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        diarium = Diarium.create! valid_attributes
        patch diarium_url(diarium), params: { diarium: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested diarium" do
      diarium = Diarium.create! valid_attributes
      expect {
        delete diarium_url(diarium)
      }.to change(Diarium, :count).by(-1)
    end

    it "redirects to the diaria list" do
      diarium = Diarium.create! valid_attributes
      delete diarium_url(diarium)
      expect(response).to redirect_to(diaria_url)
    end
  end
end
