 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/requirements", type: :request do
  # Requirement. As you add validations to Requirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Requirement.create! valid_attributes
      get requirements_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      requirement = Requirement.create! valid_attributes
      get requirement_url(requirement)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_requirement_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      requirement = Requirement.create! valid_attributes
      get edit_requirement_url(requirement)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Requirement" do
        expect {
          post requirements_url, params: { requirement: valid_attributes }
        }.to change(Requirement, :count).by(1)
      end

      it "redirects to the created requirement" do
        post requirements_url, params: { requirement: valid_attributes }
        expect(response).to redirect_to(requirement_url(Requirement.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Requirement" do
        expect {
          post requirements_url, params: { requirement: invalid_attributes }
        }.to change(Requirement, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post requirements_url, params: { requirement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested requirement" do
        requirement = Requirement.create! valid_attributes
        patch requirement_url(requirement), params: { requirement: new_attributes }
        requirement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the requirement" do
        requirement = Requirement.create! valid_attributes
        patch requirement_url(requirement), params: { requirement: new_attributes }
        requirement.reload
        expect(response).to redirect_to(requirement_url(requirement))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        requirement = Requirement.create! valid_attributes
        patch requirement_url(requirement), params: { requirement: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested requirement" do
      requirement = Requirement.create! valid_attributes
      expect {
        delete requirement_url(requirement)
      }.to change(Requirement, :count).by(-1)
    end

    it "redirects to the requirements list" do
      requirement = Requirement.create! valid_attributes
      delete requirement_url(requirement)
      expect(response).to redirect_to(requirements_url)
    end
  end
end
