# frozen_string_literal: true

require 'rails_helper'
require 'devise'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RequirementsController, type: :controller do
  let(:admin) { FactoryGirl.create :admin }
  let(:user) { FactoryGirl.create :user }

  # This should return the minimal set of attributes required to create a valid
  # Requirement. As you add validations to Requirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: 'Username', description: 'MyText' } }

  let(:invalid_attributes) { { name: nil, description: 'MyText' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequirementsController. Be sure to keep this updated too.
  let(:guest_session) {  }
  let(:admin_session) { sign_in admin }
  let(:user_session) { sign_in user }

  describe 'GET #index' do
    context 'when admin is logged in' do
      it 'returns a success response' do
        Requirement.create! valid_attributes
        get :index, params: {}, session: admin_session
        expect(response).to be_successful
      end
    end

    context 'when user is logged in' do
      it 'returns a success response' do
        Requirement.create! valid_attributes
        get :index, params: {}, session: user_session
        expect(response).to be_successful
      end
    end

    context 'when user is a guest' do
      it 'returns a success response' do
        Requirement.create! valid_attributes
        get :index, params: {}, session: guest_session
        expect(response).to be_successful
      end
    end
  end


  describe 'GET #show' do
    context 'when admin is logged in' do
      it 'returns a success response' do
        requirement = Requirement.create! valid_attributes
        get :show, params: { id: requirement.to_param }, session: admin_session
        expect(response).to be_successful
      end
    end

    context 'when user is logged in' do
      it 'returns a success response' do
        requirement = Requirement.create! valid_attributes
        get :show, params: { id: requirement.to_param }, session: user_session
        expect(response).to be_successful
      end
    end

    context 'when user is a guest' do
      it 'returns a success response' do
        requirement = Requirement.create! valid_attributes
        get :show, params: { id: requirement.to_param }, session: guest_session
        expect(response).to be_successful
      end
    end
  end

  describe 'GET #new' do
    context 'when admin is logged in' do
      it 'returns a success response' do
        get :new, params: {}, session: admin_session
        expect(response).to be_successful
      end
    end

    context 'when user is logged in' do
      it ' does not return a success response' do
        get :new, params: {}, session: user_session
        expect(response).not_to be_successful
      end
    end

    context 'when user is a guest' do
      it ' does not return a success response' do
        get :new, params: {}, session: guest_session
        expect(response).not_to be_successful
      end
    end
  end

  describe 'GET #edit' do
    context 'when admin is logged in' do
      it 'returns a success response' do
        requirement = Requirement.create! valid_attributes
        get :edit, params: { id: requirement.to_param }, session: admin_session
        expect(response).to be_successful
      end
    end
    context 'when user is logged in' do
      it ' does not return a success response' do
        requirement = Requirement.create! valid_attributes
        get :edit, params: { id: requirement.to_param }, session: user_session
        expect(response).not_to be_successful
      end
    end

    context 'when user is a guest' do
      it ' does not return a success response' do
        requirement = Requirement.create! valid_attributes
        get :edit, params: { id: requirement.to_param }, session: guest_session
        expect(response).not_to be_successful
      end
    end


  end

  describe 'POST #create' do
    context 'when admin is logged in' do
      context 'with valid params' do
        it 'creates a new Requirement' do
          expect do
            post :create, params: { requirement: valid_attributes }, session: admin_session
          end.to change(Requirement, :count).by(1)
        end

        it 'redirects to the created requirement' do
          post :create, params: { requirement: valid_attributes }, session: admin_session
          expect(response).to redirect_to(Requirement.last)
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'new' template)" do
          post :create, params: { requirement: invalid_attributes }, session: admin_session
          expect(response).to be_successful
        end
      end
    end

    context 'when user is logged in' do
      context 'with valid params' do
        it ' does not create a new Requirement' do
          expect do
            post :create, params: { requirement: valid_attributes }, session: user_session
          end.to change(Requirement, :count).by(0)
        end

        it ' does not redirect to the created requirement' do
          post :create, params: { requirement: valid_attributes }, session: user_session
          expect(response).to redirect_to(requirements_path)
        end
      end

      context 'with invalid params' do
        it " does not return a success response (i.e. to display the 'new' template)" do
          post :create, params: { requirement: invalid_attributes }, session: user_session
          expect(response).not_to be_successful
        end
      end
    end

    context 'when user is a guest' do
      context 'with valid params' do
        it ' does not create a new Requirement' do
          expect do
            post :create, params: { requirement: valid_attributes }, session: guest_session
          end.to change(Requirement, :count).by(0)
        end

        it ' does not redirect to the created requirement' do
          post :create, params: { requirement: valid_attributes }, session: guest_session
          expect(response).to redirect_to(requirements_path)
        end
      end

      context 'with invalid params' do
        it " does not return a success response (i.e. to display the 'new' template)" do
          post :create, params: { requirement: invalid_attributes }, session: guest_session
          expect(response).not_to be_successful
        end
      end
    end
  end

  describe 'PUT #update' do
    let(:new_attributes) { { name: 'Someone', description: 'AnotherText' } }
    context 'when admin is logged in' do

      context 'with valid params' do
        it 'updates the requested requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: new_attributes }, session: admin_session
          requirement.reload
          expect(requirement.name).to eq('Someone')
          expect(requirement.description).to eq('AnotherText')
        end

        it 'redirects to the requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: valid_attributes }, session: admin_session
          expect(response).to redirect_to(requirement)
        end
      end

      context 'with invalid params' do
        it "returns a success response (i.e. to display the 'edit' template)" do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: invalid_attributes }, session: admin_session
          expect(response).to be_successful
        end
      end
    end

    context 'when user is logged in' do
      context 'with valid params' do
        it ' does not update the requested requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: new_attributes }, session: user_session
          requirement.reload
          expect(requirement.name).not_to eq('Someone')
          expect(requirement.description).not_to eq('AnotherText')
        end

        it ' does not redirect to the requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: valid_attributes }, session: user_session
          expect(response).not_to redirect_to(requirement)
        end
      end

      context 'with invalid params' do
        it " does not return a success response (i.e. to display the 'edit' template)" do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: invalid_attributes }, session: user_session
          expect(response).not_to be_successful
        end
      end
    end

    context 'when user is a guest' do
      context 'with valid params' do
        it ' does not update the requested requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: new_attributes }, session: guest_session
          requirement.reload
          expect(requirement.name).not_to eq('Someone')
          expect(requirement.description).not_to eq('AnotherText')
        end

        it 'does not redirect to the requirement' do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: valid_attributes }, session: guest_session
          expect(response).not_to redirect_to(requirement)
        end
      end

      context 'with invalid params' do
        it "does not return a success response (i.e. to display the 'edit' template)" do
          requirement = Requirement.create! valid_attributes
          put :update, params: { id: requirement.to_param, requirement: invalid_attributes }, session: guest_session
          expect(response).not_to be_successful
        end
      end
    end
  end

  describe 'DELETE #destroy' do
    context 'when admin is logged in' do
      it 'destroys the requested requirement' do
        requirement = Requirement.create! valid_attributes
        expect do
          delete :destroy, params: { id: requirement.to_param }, session: admin_session
        end.to change(Requirement, :count).by(-1)
      end

      it 'redirects to the requirements list' do
        requirement = Requirement.create! valid_attributes
        delete :destroy, params: { id: requirement.to_param }, session: admin_session
        expect(response).to redirect_to(requirements_url)
      end
    end

    context 'when user is logged in' do
      it 'does not destroy the requested requirement' do
        requirement = Requirement.create! valid_attributes
        expect do
          delete :destroy, params: { id: requirement.to_param }, session: user_session
        end.to change(Requirement, :count).by(0)
      end

      it 'does not redirect to the requirements list' do
        requirement = Requirement.create! valid_attributes
        delete :destroy, params: { id: requirement.to_param }, session: user_session
        expect(response).to redirect_to(requirements_url)
      end
    end

    context 'when user is a guest' do
      it 'does not destroy the requested requirement' do
        requirement = Requirement.create! valid_attributes
        expect do
          delete :destroy, params: { id: requirement.to_param }, session: guest_session
        end.to change(Requirement, :count).by(0)
      end

      it 'does not redirect to the requirements list' do
        requirement = Requirement.create! valid_attributes
        delete :destroy, params: { id: requirement.to_param }, session: guest_session
        expect(response).to redirect_to(requirements_url)
      end
    end
  end
end
