require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RequirementsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Requirement. As you add validations to Requirement, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    file = fixture_file_upload(Rails.root.join('public', 'TestImage.png'), 'image/png')
    {"title" => "test", "content" => "", "documents" => [file]}
  }

  let(:invalid_attributes) {
    {"title" => ""}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RequirementsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      Requirement.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      requirement = Requirement.create! valid_attributes
      get :show, params: {id: requirement.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      requirement = Requirement.create! valid_attributes
      get :edit, params: {id: requirement.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Requirement" do
        expect {
          post :create, params: {requirement: valid_attributes}, session: valid_session
        }.to change(Requirement, :count).by(1)
      end

      it "redirects to the created requirement" do
        post :create, params: {requirement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Requirement.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {requirement: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested requirement" do
        requirement = Requirement.create! valid_attributes
        put :update, params: {id: requirement.to_param, requirement: new_attributes}, session: valid_session
        requirement.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the requirement" do
        requirement = Requirement.create! valid_attributes
        put :update, params: {id: requirement.to_param, requirement: valid_attributes}, session: valid_session
        expect(response).to redirect_to(requirement)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        requirement = Requirement.create! valid_attributes
        put :update, params: {id: requirement.to_param, requirement: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "Documents Management"do
    it 'purges a specific file' do
      requirement = Requirement.create! valid_attributes
      requirement.documents.each do | document |
        expect {
          delete :delete_document_attachment, params: { id: document.id, requirement_id: requirement.id }
        }.to change(ActiveStorage::Attachment, :count).by(-1)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested requirement" do
      requirement = Requirement.create! valid_attributes
      expect {
        delete :destroy, params: {id: requirement.to_param}, session: valid_session
      }.to change(Requirement, :count).by(-1)
    end

    it "redirects to the requirements list" do
      requirement = Requirement.create! valid_attributes
      delete :destroy, params: {id: requirement.to_param}, session: valid_session
      expect(response).to redirect_to(requirements_url)
    end
  end

end
